# uri: '/', '/news' и тп
routes:
    '/':
        method: GET
        controller: App\Controller\IndexAction
    '/news':
        method: GET
        controller: App\Controller\NewsAction
    '/news/:id':
        method: GET
        controller: App\Controller\NewsItemAction
