# uri: '/', '/news' и тп
routes:
    '/':
        method: GET
        action: App\Controller\IndexAction
    '/news':
        method: GET
        action: App\Controller\NewsCollectionAction
    '/news/:id':
        method: GET
        action: App\Controller\NewsItemAction
